CREATE TABLE USUARIOS (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(200),
    PASSWORD VARCHAR(500)
);

CREATE TABLE EXPENSES (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    DESCRIPTION VARCHAR(100),
    PRIMARIGUID VARCHAR(100)
    PRICE DOUBLE;
)